unique_ids:
  assets:
    standard-page.html: ZQJIBKRMRNDD2FSINQJ3E4A6CEAAMY2U
    theme.css: TZXK3QLOHB2YWWWIPAPG7GRJ2YYOGDGH
  forms:
    Form1: D3HUNE2EXMZFPOENZXQ3TSXR6NRXCYSD
  modules: {}
  scripts: {}
  server_modules: {}
